apiVersion: flightctl.io/v1beta1
kind: ResourceSync
metadata:
  name: davenport-diag-sync
spec:
  repository: davenport-diag
  path: /simulator/rhem/deployment/davenport_diag.yaml
  targetRevision: main